### ISSUE TITLE
Feature: add royalty

### ISSUE THREAD

**Issue by ls-bob** [eforest-finance/forest-interface#234]
-  After a successful NFT transaction, creators can collect royalties
- If creators want to collect royalties, they can configure the royalty ratio and receive a certain percentage of royalties after 
   successful NFT transactions

**Comment by fyannch** [comment]
### Expected Behavior
After a successful NFT transaction, creators can collect royalties
### Specifications
**Features:**
- 1、Contract adds royalty configuration and query methods
- 2、Upon completion of the transaction, royalties will be deducted proportionally and transferred to the creator
- 3、Add royalty configuration query API on the server side

**Development Tasks:**

### Dependencies
### References
